### ISSUE TITLE
代码块显示优化

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/blog-github-api-angular#36]
参考效果：https://www.stavros.io/posts/example-provisioning-and-deployment-ansible/

**Comment by JimmyLv** [comment]
参考效果：https://www.stavros.io/posts/example-provisioning-and-deployment-ansible/

**Comment by EthanLin-TWer** [comment]
老实说看了链接觉得这个代码效果过犹不及。

**Comment by JimmyLv** [comment]
@linesh-simplicity 不符合目前网站的风格，所以 close 好了。

其实比较适合两边巨大留白的网站，效果可以再设计设计，不局限于展开，比如原本没有高亮，鼠标 hover 竟然出现高亮，哈哈哈哈~

**Comment by EthanLin-TWer** [comment]
嗯嗯～哈哈哈，其实hover上去弹出东西来，会不会猛然吓一跳，然后视线就被转移了啊~~
