### ISSUE TITLE
语法高亮

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/blog-github-api-angular#43]
语法高亮：highlight.js > google-code-prettify (options.codeClass="prettyprint")

小坑： hljs.getLanguage(lang)

**Comment by JimmyLv** [comment]
<img width="937" alt="screen 5" src="https://cloud.githubusercontent.com/assets/4997466/13695532/9e501aa6-e79a-11e5-8c5d-efe99fb2bd97.png">

**Comment by EthanLin-TWer** [comment]
楼上是个截图以为我没发现吗。来来安利一款插件划过图片马上加载原图哈哈哈～

**Comment by JimmyLv** [comment]
@linesh-simplicity 图片加载完，真是异常得好看啊喂。

**Comment by EthanLin-TWer** [comment]
@JimmyLv 卧槽发现你的这个代码高亮配色非常好看！！！用了Hightlightjs是么～

**Comment by JimmyLv** [comment]
@linesh-simplicity 啊哈，就是这样的，配色在[这里](https://highlightjs.org/static/demo/)找 Kimbie (light)。
