### ISSUE TITLE
平台化，抽取配置

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/blog-github-api-angular#56]
- 抽取到`_config.yml`
  - [x] playlist
  - [x] github
  - [x] path
  - [x] local
  - [ ] api
- fork 即用

**Comment by EthanLin-TWer** [comment]
点赞，这个博客做完也相当一个“API”发布出去啊，API可配置用起来就方便。

**Comment by JimmyLv** [comment]
@linesh-simplicity 嗯，就跟 jekyll 一样一样的，最好做到 GitHub 授权登录就直接可用。

**Comment by JimmyLv** [comment]
@linesh-simplicity 就是说，用 GitHub 登录之后，直接就进入后台管理界面，就可以在网页上写作啦，完美上手体验，编辑体验。（不过放到 v2.0 吧，哈哈哈）
