### ISSUE TITLE
Vue 版本先行 到 放弃

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/blog-github-api-angular#77]
~~then, 使用 Vuex / Redux~~

从入门到放弃 Vue：生态！生态！生态！
- （非本人）吐槽一下vue-loader : https://segmentfault.com/a/1190000004944322
- 搜到的 Vue 相关视频的后端全是 PHP，只是说明 Vue 对原来写 HTML 的人特别友好
- 优点当然是绝对的小而美，但是社区确实太弱了，都靠 @yyx990803 Evan You 一个人
- 像我这种依赖 IDE 的人，没有完整的工具链，（在 Intellij 系列中，现有的两个插件 [vuejs-plugin](https://github.com/postalservice14/vuejs-plugin) 和 [vue-for-idea](https://github.com/henjue/vue-for-idea) 的支持都还不够，& [vue-syntax-highlight](https://github.com/vuejs/vue-syntax-highlight/issues/3)）连个语法高亮都木有，写起东西来真的很痛苦。
- [immutable.js 中毒](https://www.youtube.com/watch?v=YFP8lbdZ0cs)，Redux 与 FB，不可变是很多设计的基础，而 Vuex 却决定不这么干，当然也是有意而为之。

再夸一夸：
- [概述](http://vuejs.org.cn/guide/overview.html)，以及非常棒的[系列视频](https://laracasts.com/series/learning-vue-step-by-step/episodes/9?autoplay=true)
  - 使用 MVVM 实现的响应式数据绑定，确实很赞，可以学到的最核心的思想就是，面向数据编程；
  - 通过 Vue 来学习 MVVM 思想，是要比 Angular 要清晰到哪里去了的；
  - 同一个 vue 组件同时包含 js/html/css，再也不用频繁切换 3+ 文件了，组件系统组织起来也很简单；
- [绑定](http://vuejs.org.cn/guide/syntax.html)，以及 [styling 上的绑定](http://vuejs.org.cn/guide/class-and-style.html):
  - [缩写非常简洁](%28http://vuejs.org.cn/guide/syntax.html#u7F29_u5199%29)，但是又回到了 Angular 2 的问题，在 HTML 当中插入过多语法糖，虽然没有过多，但还是有绑定方式的困扰。
  - [绑定快捷键](http://vuejs.org.cn/guide/events.html#按键修饰符)的那个部分让人特别惊艳，一种串联式的写法，监听事件，总之让我学到 API 的简洁之美。
- 组件内现成 properties，一种形而上的抽象：http://vuejs.org.cn/examples/commits.html
  - el  data   computed created   watch   filters   methods 
- 其他：
  - 路由设计让我懂了 ui-router：http://router.vuejs.org/zh-cn/named.html | https://youtu.be/QN7l3ydXvx0?list=PLyn6qgzq5UGmm0Lo39OLj_cWOAO7G5uG8
  - 作者对 Vue 的介绍：http://www.csdn.net/article/2015-08-11/2825439-vue
  - 源码分析：http://jiongks.name/blog/vue-code-review/

一些不错的项目和例子：
- http://vuejs.org.cn/examples
- https://github.com/astralapp/astral
- https://github.com/vuejs-templates/webpack
- https://github.com/vuejs/vue-hackernews

**Comment by yyx990803** [comment]
你吐槽就算了，还 at 我... 这个直接发到我邮箱的好吗...

连语法高亮都没有，你确定你看过 [awesome-vue](https://github.com/vuejs/awesome-vue#syntax-highlighting)？连生态的圈都没入就抱怨没生态，我能说什么呢？

对于 vue-loader 的吐槽，感觉其实很弱哎，webpack 推荐怎么做没必要当做金科玉律，loader 本来就分为 utility loader 和 meta loader 两种，vue-loader 是一个 meta loader，也就是把一个 vue 文件分解然后分流给其他 loader 的 loader。这个 technique 还是 webpack 作者自己传授的。

实质上你抱怨的不能 chain 也是一个伪命题，因为 vue-loader 本来就不是拿来 chain 的。vue-loader 本身真正的内容是三块东西里面的内容，而你可以通过配置 webpack config 里面的 vue 选项对三块内容自定义任意 loader。往后 chain 也是无意义的，因为改写代码产生副作用的 loader 比如 style-loader 也是不能 chain 的。你觉得这个有问题只能说你对 webpack loader 见识得太少...

**Comment by yyx990803** [comment]
生态比 React 弱自然没办法，不过你要吐槽请吐到点上。至于用不用你随意。

**Comment by egoist** [comment]
夭寿啦，这样（手动滑稽的吐槽作者也来回复真是令人感动。

P.S. 

> 像我这种依赖 IDE 的人，没有完整的工具链，连个语法高亮都木有，写起东西来真的很痛苦。

我有个朋友的同事，她不知道 Vue 有高亮，所以每次在 IDE 里写了 HTML 之后再粘贴到 `.vue` 文件里 😂
